package com.springapp.mvc;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.LoginForm;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.TabSheet;

public class trial extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_2;
	@AutoGenerated
	private HorizontalSplitPanel horizontalSplitPanel_4;
	@AutoGenerated
	private TabSheet tab;
	@AutoGenerated
	private RichTextArea richTextArea_2;
	@AutoGenerated
	private NativeSelect nativeSelect_1;
	@AutoGenerated
	private LoginForm loginForm_7;
	@AutoGenerated
	private Button back;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public trial() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// absoluteLayout_2
		absoluteLayout_2 = buildAbsoluteLayout_2();
		mainLayout.addComponent(absoluteLayout_2, "top:20.0px;left:10.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_2() {
		// common part: create layout
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth("710px");
		absoluteLayout_2.setHeight("520px");
		
		// back
		back = new Button();
		back.setCaption("Back");
		back.setImmediate(false);
		back.setWidth("-1px");
		back.setHeight("-1px");
		absoluteLayout_2.addComponent(back, "top:24.0px;left:15.0px;");
		
		// horizontalSplitPanel_4
		horizontalSplitPanel_4 = buildHorizontalSplitPanel_4();
		absoluteLayout_2.addComponent(horizontalSplitPanel_4,
				"top:100.0px;left:30.0px;");
		
		return absoluteLayout_2;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildHorizontalSplitPanel_4() {
		// common part: create layout
		horizontalSplitPanel_4 = new HorizontalSplitPanel();
		horizontalSplitPanel_4.setImmediate(false);
		horizontalSplitPanel_4.setWidth("640px");
		horizontalSplitPanel_4.setHeight("440px");
		
		// tab
		tab = buildTab();
		horizontalSplitPanel_4.addComponent(tab);
		
		return horizontalSplitPanel_4;
	}

	@AutoGenerated
	private TabSheet buildTab() {
		// common part: create layout
		tab = new TabSheet();
		tab.setImmediate(true);
		tab.setWidth("300px");
		tab.setHeight("240px");
		
		// loginForm_7
		loginForm_7 = new LoginForm();
		loginForm_7.setStyleName("v-loginform");
		loginForm_7.setImmediate(false);
		loginForm_7.setWidth("100.0%");
		loginForm_7.setHeight("100.0%");
		tab.addTab(loginForm_7, "Login", null);
		
		// nativeSelect_1
		nativeSelect_1 = new NativeSelect();
		nativeSelect_1.setImmediate(false);
		nativeSelect_1.setWidth("-1px");
		nativeSelect_1.setHeight("-1px");
		tab.addTab(nativeSelect_1, "Option", null);
		
		// richTextArea_2
		richTextArea_2 = new RichTextArea();
		richTextArea_2.setImmediate(false);
		richTextArea_2.setWidth("309px");
		richTextArea_2.setHeight("-1px");
		tab.addTab(richTextArea_2, "Feedback", null);
		
		return tab;
	}

}
